name = "ImagingOpt"
uuid = "32c1e3af-154a-49cc-8f65-da7861a92a28"
authors = ["Gaurav Arya <gauravarya272@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Augmentor = "02898b10-1f73-11ea-317c-6393d7073e15"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FLoops = "cc61a311-1640-44b5-9fba-1b764f453329"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
ImplicitAdjoints = "dc78e922-f45c-41f9-88f5-a5d7bf3a9742"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
NaturalSort = "c020b1a1-e9b0-503a-9c33-f039bfc54a85"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
ShiftedArrays = "1277b4bf-5013-50f5-be3d-901d8477a67a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
WavePropagation = "35738e4c-42fb-4913-b8e7-4cd0bbf068f1"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Zygote = "0.6"
StructTypes = "1"
JSON3 = "1"
Optimisers = "0.2"
Images = "0.25"
FFTW = "1"
TestImages = "1"
ShiftedArrays = "1"
FiniteDifferences = "0.12"
Setfield = "1"
LinearMaps = "<3.9"
MAT = "0.10"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
